<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Deterministic>true</Deterministic>
        <PublishAot>true</PublishAot>
        <RootNamespace>ImGuiWindows</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Silk.NET\sources\Core\Core\Silk.NET.Core.csproj" />
      <ProjectReference Include="..\Silk.NET\sources\Input\Input\Silk.NET.Input.csproj" />
      <ProjectReference Include="..\Silk.NET\sources\Maths\Maths\Silk.NET.Maths.csproj" />
      <ProjectReference Include="..\Silk.NET\sources\SDL\SDL\Silk.NET.SDL.csproj" />
      <ProjectReference Include="..\Silk.NET\sources\Windowing\Windowing\Silk.NET.Windowing.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    </ItemGroup>

</Project>