using System.Collections.Frozen;
using System.Runtime.CompilerServices;
using ImGuiNET;
using Silk.NET.Input;

namespace ImGuiWindows;

public static class InputExtensions
{
    private static readonly FrozenDictionary<KeyName, ImGuiKey> KeyNameToImGuiKeyMap =
        new Dictionary<KeyName, ImGuiKey>
        {
            [KeyName.Tab] = ImGuiKey.Tab,
            [KeyName.Left] = ImGuiKey.LeftArrow,
            [KeyName.Right] = ImGuiKey.RightArrow,
            [KeyName.Up] = ImGuiKey.UpArrow,
            [KeyName.Down] = ImGuiKey.DownArrow,
            [KeyName.PageUp] = ImGuiKey.PageUp,
            [KeyName.PageDown] = ImGuiKey.PageDown,
            [KeyName.Home] = ImGuiKey.Home,
            [KeyName.End] = ImGuiKey.End,
            [KeyName.Insert] = ImGuiKey.Insert,
            [KeyName.Delete] = ImGuiKey.Delete,
            [KeyName.Backspace] = ImGuiKey.Backspace,
            [KeyName.Space] = ImGuiKey.Space,
            [KeyName.Return] = ImGuiKey.Enter,
            [KeyName.Escape] = ImGuiKey.Escape,
            [KeyName.Apostrophe] = ImGuiKey.Apostrophe,
            [KeyName.Comma] = ImGuiKey.Comma,
            [KeyName.Minus] = ImGuiKey.Minus,
            [KeyName.Period] = ImGuiKey.Period,
            [KeyName.Slash] = ImGuiKey.Slash,
            [KeyName.Semicolon] = ImGuiKey.Semicolon,
            [KeyName.Equals] = ImGuiKey.Equal,
            [KeyName.LeftBracket] = ImGuiKey.LeftBracket,
            [KeyName.Backslash] = ImGuiKey.Backslash,
            [KeyName.RightBracket] = ImGuiKey.RightBracket,
            [KeyName.Grave] = ImGuiKey.GraveAccent,
            [KeyName.CapsLock] = ImGuiKey.CapsLock,
            [KeyName.ScrollLock] = ImGuiKey.ScrollLock,
            // [KeyName.NumLock] = ImGuiKey.NumLock,
            [KeyName.PrintScreen] = ImGuiKey.PrintScreen,
            [KeyName.Pause] = ImGuiKey.Pause,
            [KeyName.Keypad0] = ImGuiKey.Keypad0,
            [KeyName.Keypad1] = ImGuiKey.Keypad1,
            [KeyName.Keypad2] = ImGuiKey.Keypad2,
            [KeyName.Keypad3] = ImGuiKey.Keypad3,
            [KeyName.Keypad4] = ImGuiKey.Keypad4,
            [KeyName.Keypad5] = ImGuiKey.Keypad5,
            [KeyName.Keypad6] = ImGuiKey.Keypad6,
            [KeyName.Keypad7] = ImGuiKey.Keypad7,
            [KeyName.Keypad8] = ImGuiKey.Keypad8,
            [KeyName.Keypad9] = ImGuiKey.Keypad9,
            [KeyName.KeypadDecimal] = ImGuiKey.KeypadDecimal,
            [KeyName.KeypadDivide] = ImGuiKey.KeypadDivide,
            [KeyName.KeypadMultiply] = ImGuiKey.KeypadMultiply,
            [KeyName.KeypadMinus] = ImGuiKey.KeypadSubtract,
            [KeyName.KeypadPlus] = ImGuiKey.KeypadAdd,
            [KeyName.KeypadEnter] = ImGuiKey.KeypadEnter,
            [KeyName.KeypadEquals] = ImGuiKey.KeypadEqual,
            [KeyName.OtherKeypadEquals] = ImGuiKey.KeypadEqual,
            [KeyName.ShiftLeft] = ImGuiKey.LeftShift,
            [KeyName.ControlLeft] = ImGuiKey.LeftCtrl,
            [KeyName.AltLeft] = ImGuiKey.LeftAlt,
            [KeyName.SuperLeft] = ImGuiKey.LeftSuper,
            [KeyName.ShiftRight] = ImGuiKey.RightShift,
            [KeyName.ControlRight] = ImGuiKey.RightCtrl,
            [KeyName.AltRight] = ImGuiKey.RightAlt,
            [KeyName.SuperRight] = ImGuiKey.RightSuper,
            [KeyName.Menu] = ImGuiKey.Menu,
            [KeyName.Number0] = ImGuiKey._0,
            [KeyName.Number1] = ImGuiKey._1,
            [KeyName.Number2] = ImGuiKey._2,
            [KeyName.Number3] = ImGuiKey._3,
            [KeyName.Number4] = ImGuiKey._4,
            [KeyName.Number5] = ImGuiKey._5,
            [KeyName.Number6] = ImGuiKey._6,
            [KeyName.Number7] = ImGuiKey._7,
            [KeyName.Number8] = ImGuiKey._8,
            [KeyName.Number9] = ImGuiKey._9,
            [KeyName.A] = ImGuiKey.A,
            [KeyName.B] = ImGuiKey.B,
            [KeyName.C] = ImGuiKey.C,
            [KeyName.D] = ImGuiKey.D,
            [KeyName.E] = ImGuiKey.E,
            [KeyName.F] = ImGuiKey.F,
            [KeyName.G] = ImGuiKey.G,
            [KeyName.H] = ImGuiKey.H,
            [KeyName.I] = ImGuiKey.I,
            [KeyName.J] = ImGuiKey.J,
            [KeyName.K] = ImGuiKey.K,
            [KeyName.L] = ImGuiKey.L,
            [KeyName.M] = ImGuiKey.M,
            [KeyName.N] = ImGuiKey.N,
            [KeyName.O] = ImGuiKey.O,
            [KeyName.P] = ImGuiKey.P,
            [KeyName.Q] = ImGuiKey.Q,
            [KeyName.R] = ImGuiKey.R,
            [KeyName.S] = ImGuiKey.S,
            [KeyName.T] = ImGuiKey.T,
            [KeyName.U] = ImGuiKey.U,
            [KeyName.V] = ImGuiKey.V,
            [KeyName.W] = ImGuiKey.W,
            [KeyName.X] = ImGuiKey.X,
            [KeyName.Y] = ImGuiKey.Y,
            [KeyName.Z] = ImGuiKey.Z,
            [KeyName.F1] = ImGuiKey.F1,
            [KeyName.F2] = ImGuiKey.F2,
            [KeyName.F3] = ImGuiKey.F3,
            [KeyName.F4] = ImGuiKey.F4,
            [KeyName.F5] = ImGuiKey.F5,
            [KeyName.F6] = ImGuiKey.F6,
            [KeyName.F7] = ImGuiKey.F7,
            [KeyName.F8] = ImGuiKey.F8,
            [KeyName.F9] = ImGuiKey.F9,
            [KeyName.F10] = ImGuiKey.F10,
            [KeyName.F11] = ImGuiKey.F11,
            [KeyName.F12] = ImGuiKey.F12,
            [KeyName.F13] = ImGuiKey.F13,
            [KeyName.F14] = ImGuiKey.F14,
            [KeyName.F15] = ImGuiKey.F15,
            [KeyName.F16] = ImGuiKey.F16,
            [KeyName.F17] = ImGuiKey.F17,
            [KeyName.F18] = ImGuiKey.F18,
            [KeyName.F19] = ImGuiKey.F19,
            [KeyName.F20] = ImGuiKey.F20,
            [KeyName.F21] = ImGuiKey.F21,
            [KeyName.F22] = ImGuiKey.F22,
            [KeyName.F23] = ImGuiKey.F23,
            [KeyName.F24] = ImGuiKey.F24,
        }.ToFrozenDictionary();

    private static readonly FrozenDictionary<ImGuiKey, KeyName> ImGuiKeyToKeyNameMap =
        new Dictionary<ImGuiKey, KeyName>
        {
            [ImGuiKey.Tab] = KeyName.Tab,
            [ImGuiKey.LeftArrow] = KeyName.Left,
            [ImGuiKey.RightArrow] = KeyName.Right,
            [ImGuiKey.UpArrow] = KeyName.Up,
            [ImGuiKey.DownArrow] = KeyName.Down,
            [ImGuiKey.PageUp] = KeyName.PageUp,
            [ImGuiKey.PageDown] = KeyName.PageDown,
            [ImGuiKey.Home] = KeyName.Home,
            [ImGuiKey.End] = KeyName.End,
            [ImGuiKey.Insert] = KeyName.Insert,
            [ImGuiKey.Delete] = KeyName.Delete,
            [ImGuiKey.Backspace] = KeyName.Backspace,
            [ImGuiKey.Space] = KeyName.Space,
            [ImGuiKey.Enter] = KeyName.Return,
            [ImGuiKey.Escape] = KeyName.Escape,
            [ImGuiKey.Apostrophe] = KeyName.Apostrophe,
            [ImGuiKey.Comma] = KeyName.Comma,
            [ImGuiKey.Minus] = KeyName.Minus,
            [ImGuiKey.Period] = KeyName.Period,
            [ImGuiKey.Slash] = KeyName.Slash,
            [ImGuiKey.Semicolon] = KeyName.Semicolon,
            [ImGuiKey.Equal] = KeyName.Equals,
            [ImGuiKey.LeftBracket] = KeyName.LeftBracket,
            [ImGuiKey.Backslash] = KeyName.Backslash,
            [ImGuiKey.RightBracket] = KeyName.RightBracket,
            [ImGuiKey.GraveAccent] = KeyName.Grave,
            [ImGuiKey.CapsLock] = KeyName.CapsLock,
            [ImGuiKey.ScrollLock] = KeyName.ScrollLock,
            [ImGuiKey.PrintScreen] = KeyName.PrintScreen,
            [ImGuiKey.Pause] = KeyName.Pause,
            [ImGuiKey.Keypad0] = KeyName.Keypad0,
            [ImGuiKey.Keypad1] = KeyName.Keypad1,
            [ImGuiKey.Keypad2] = KeyName.Keypad2,
            [ImGuiKey.Keypad3] = KeyName.Keypad3,
            [ImGuiKey.Keypad4] = KeyName.Keypad4,
            [ImGuiKey.Keypad5] = KeyName.Keypad5,
            [ImGuiKey.Keypad6] = KeyName.Keypad6,
            [ImGuiKey.Keypad7] = KeyName.Keypad7,
            [ImGuiKey.Keypad8] = KeyName.Keypad8,
            [ImGuiKey.Keypad9] = KeyName.Keypad9,
            [ImGuiKey.KeypadDecimal] = KeyName.KeypadDecimal,
            [ImGuiKey.KeypadDivide] = KeyName.KeypadDivide,
            [ImGuiKey.KeypadMultiply] = KeyName.KeypadMultiply,
            [ImGuiKey.KeypadSubtract] = KeyName.KeypadMinus,
            [ImGuiKey.KeypadAdd] = KeyName.KeypadPlus,
            [ImGuiKey.KeypadEnter] = KeyName.KeypadEnter,
            [ImGuiKey.KeypadEqual] = KeyName.KeypadEquals,
            [ImGuiKey.LeftShift] = KeyName.ShiftLeft,
            [ImGuiKey.LeftCtrl] = KeyName.ControlLeft,
            [ImGuiKey.LeftAlt] = KeyName.AltLeft,
            [ImGuiKey.LeftSuper] = KeyName.SuperLeft,
            [ImGuiKey.RightShift] = KeyName.ShiftRight,
            [ImGuiKey.RightCtrl] = KeyName.ControlRight,
            [ImGuiKey.RightAlt] = KeyName.AltRight,
            [ImGuiKey.RightSuper] = KeyName.SuperRight,
            [ImGuiKey.Menu] = KeyName.Menu,
            [ImGuiKey._0] = KeyName.Number0,
            [ImGuiKey._1] = KeyName.Number1,
            [ImGuiKey._2] = KeyName.Number2,
            [ImGuiKey._3] = KeyName.Number3,
            [ImGuiKey._4] = KeyName.Number4,
            [ImGuiKey._5] = KeyName.Number5,
            [ImGuiKey._6] = KeyName.Number6,
            [ImGuiKey._7] = KeyName.Number7,
            [ImGuiKey._8] = KeyName.Number8,
            [ImGuiKey._9] = KeyName.Number9,
            [ImGuiKey.A] = KeyName.A,
            [ImGuiKey.B] = KeyName.B,
            [ImGuiKey.C] = KeyName.C,
            [ImGuiKey.D] = KeyName.D,
            [ImGuiKey.E] = KeyName.E,
            [ImGuiKey.F] = KeyName.F,
            [ImGuiKey.G] = KeyName.G,
            [ImGuiKey.H] = KeyName.H,
            [ImGuiKey.I] = KeyName.I,
            [ImGuiKey.J] = KeyName.J,
            [ImGuiKey.K] = KeyName.K,
            [ImGuiKey.L] = KeyName.L,
            [ImGuiKey.M] = KeyName.M,
            [ImGuiKey.N] = KeyName.N,
            [ImGuiKey.O] = KeyName.O,
            [ImGuiKey.P] = KeyName.P,
            [ImGuiKey.Q] = KeyName.Q,
            [ImGuiKey.R] = KeyName.R,
            [ImGuiKey.S] = KeyName.S,
            [ImGuiKey.T] = KeyName.T,
            [ImGuiKey.U] = KeyName.U,
            [ImGuiKey.V] = KeyName.V,
            [ImGuiKey.W] = KeyName.W,
            [ImGuiKey.X] = KeyName.X,
            [ImGuiKey.Y] = KeyName.Y,
            [ImGuiKey.Z] = KeyName.Z,
            [ImGuiKey.F1] = KeyName.F1,
            [ImGuiKey.F2] = KeyName.F2,
            [ImGuiKey.F3] = KeyName.F3,
            [ImGuiKey.F4] = KeyName.F4,
            [ImGuiKey.F5] = KeyName.F5,
            [ImGuiKey.F6] = KeyName.F6,
            [ImGuiKey.F7] = KeyName.F7,
            [ImGuiKey.F8] = KeyName.F8,
            [ImGuiKey.F9] = KeyName.F9,
            [ImGuiKey.F10] = KeyName.F10,
            [ImGuiKey.F11] = KeyName.F11,
            [ImGuiKey.F12] = KeyName.F12,
            [ImGuiKey.F13] = KeyName.F13,
            [ImGuiKey.F14] = KeyName.F14,
            [ImGuiKey.F15] = KeyName.F15,
            [ImGuiKey.F16] = KeyName.F16,
            [ImGuiKey.F17] = KeyName.F17,
            [ImGuiKey.F18] = KeyName.F18,
            [ImGuiKey.F19] = KeyName.F19,
            [ImGuiKey.F20] = KeyName.F20,
            [ImGuiKey.F21] = KeyName.F21,
            [ImGuiKey.F22] = KeyName.F22,
            [ImGuiKey.F23] = KeyName.F23,
            [ImGuiKey.F24] = KeyName.F24,
        }.ToFrozenDictionary();

    extension(ImGuiKey key)
    {
        /// <summary>
        /// Translates an ImGuiKey to the canonical Silk.NET.Input.KeyName.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public KeyName ToKeyName() => ImGuiKeyToKeyNameMap.GetValueOrDefault(key);

        /// <summary>
        /// Tries to translate an ImGuiKey to the canonical Silk.NET.Input.KeyName.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool ToKeyName(out KeyName keyName) => ImGuiKeyToKeyNameMap.TryGetValue(key, out keyName);
    }

    extension(KeyName key)
    {
        /// <summary>
        /// Translates a Silk.NET.Input.KeyName to an ImGuiKey.
        /// Alias keys are supported.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImGuiKey ToImGuiKey() => KeyNameToImGuiKeyMap.GetValueOrDefault(key, ImGuiKey.None);

        /// <summary>
        /// Tries to translate a Silk.NET.Input.KeyName to an ImGuiKey.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool ToImGuiKey(out ImGuiKey imGuiKey) => KeyNameToImGuiKeyMap.TryGetValue(key, out imGuiKey);
    }
}
